#!/bin/bash

#shellcheck disable=SC2010,2154,1091

# TODO: spicetify, tmux, vim

# LOADING SHARED FILE

if [[ -f $(pwd)/shared ]]; then
    source shared
else
    echo "missing file: shared"
    exit 1
fi

install_os_utils() {
    print_title "[!] INSTALLING OS UTILITIES"
    sudo pacman -Sy --noconfirm cmake bc rsync mlocate bash-completion pkgstats git go curl wget zsh \
                    atop htop neofetch zip unzip unrar p7zip lzop cpio ntfs-3g python python-pip \
                    dosfstools exfat-utils f2fs-tools fuse fuse-exfat autofs mtpfs cmus shellcheck jq mate-polkit \
                    molecule playerctl firefox chromium caja mat2 firejail ebtables dnsmasq meson ninja gtkmm3
}

install_nfs() {
    print_title "[!] ENABLING NFS"
    sudo systemctl enable rpcbind
    sudo systemctl enable nfs-client.target
    sudo systemctl enable remote-fs.target
}

# TODO: hostblock, doas, rmlint, tripwire, aide, checksec, lynis

install_secpack() {
    print_title "[!] INSTALLING SECURITY TOOLS"
    sudo pacman -Sy --noconfirm rkhunter clamav logwatch
    #yay -Sy --answerclean A --answerdiff N aide
    sudo systemctl enable clamav-daemon
    sudo freshclam -d -c 1
    sudo rkhunter --propupd
    sudo rkhunter --update
}

# Install audio utilities

install_audio() {
    print_title "[!] INSTALLING AUDIO TOOLS"
    sudo pacman -Sy --noconfirm alsa-utils alsa-plugins pulseaudio pulseaudio-alsa pavucontrol
}

# Install Blutooth

install_bluetooth() {
    print_title "[!] INSTALLING BLUETOOTH"
    BLZ=$(dmesg | grep -c Blue)
    if [[ $BLZ -gt 0 ]]; then
        read -p "Want to install Bluetooth? [Y/n]" -n 1 -r
        echo
        REPLY=${REPLY:-Y}
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            sudo pacman -Sy --noconfirm bluez bluez-utils pulseaudio-bluetooth blueman
            syudo systemctl enable bluetooth
        fi
    fi
}

# Install colored utilities

install_colored() {
    print_title "[!] INSTALLING COLORED UTILS"
    sudo pacman -Sy --noconfirm lsd bat grc
}

# Install Amd GPU

install_gpu() {
    print_title "[!] INSTALLING AMD GPU"
    read_input_text "Want to install AMD GPU?"
    if [[ $OPTION == y ]]; then
        sudo pacman -Sy --noconfirm xf86-video-amdgpu vulkan-radeon vulkan-tools mesa-libgl mesa-vdpau libvdpau-va-gl
        add_module "amdgpu radeon" "ati"
        if [ "$(ls /boot | grep hardened -c)" -gt "0" ]; then
            sudo mkinitcpio -p linux-hardened
        elif [ "$(ls /boot | grep lts -c)" -gt "0" ]; then
            sudo mkinitcpio -p linux-lts
        elif [ "$(ls /boot | grep zen -c)" -gt "0" ]; then
            sudo mkinitcpio -p linux-zen
        else
            sudo mkinitcpio -p linux
        fi
    fi
}

# Install Yay

install_yay() {
    print_title "[!] INSTALLING YAY"
    cd /tmp || exit
    git clone https://aur.archlinux.org/yay.git
    cd yay || exit
    makepkg -csi --noconfirm
}

# Installing oh-my-zsh and plugins

install_zsh_plugins() {
    print_title "[!] INSTALLING ZSH PLUGINS"
    sh -c \\"$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)\\"
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/themes/powerlevel10k
    git clone https://github.com/zsh-users/zsh-completions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-completions
    git clone https://github.com/zsh-users/zsh-autosuggestions "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-autosuggestions
    git clone https://github.com/zsh-users/zsh-syntax-highlighting.git "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}"/plugins/zsh-syntax-highlighting
}

# Configuring sddm

configure_sddm() {
    print_title "[!] CONFIGURING SDDM"
    sudo pacman -Sy qt5-graphicaleffects sddm
    cd /tmp || exit
    git clone https://github.com/RadRussianRus/sddm-slice.git
    sed -i '3 s/background=/background=~\/.images\/AbstractViolet.png/g' sddm-slice/theme.conf
    cp sddm-slice/theme.conf sdmm-slice/theme.conf.user
    sudo cp -r sddm-slice /usr/share/sddm/themes/sddm-slice
    sudo mkdir /etc/sddm.conf.d
    sudo cp /usr/lib/sddm/sddm.conf.d/default.conf /etc/sddm.conf.d/
    sudo sed -i '33 s/Current=/Current=sddm-slice/g' /etc/sddm.conf.d/default.conf
    sudo systemctl enable sddm
}

# Configuring DNS In order to work properly with vpns.

configure_dns() {
    print_title "[!] CONFIGURING DNS"
    sudo rm /etc/resolv.conf
    sudo ln -s /run/NetworkManager/resolv.conf /etc/resolv.conf
    echo "enabled=false" >> /usr/lib/NetworkManager/conf.d/20-connectivity.conf
}

# Install Virtualization

install_virtualbox() {
    print_title "[!] INSTALLING virtualbox"
    echo "todo"
    sudo pacmann -Sy --noconfirm base-devel dkms
    wget -c
    wget -c
    sudo chmdo +x 
}

install_kvm() {
    print_title "[!] INSTALLING qemu/kvm"
    echo "todo"
    sudo pacman -Sy libvirt virt-manager
    sudo usermod -aG libvirt "$USER"
    sudo usermod -aG kvm "$USER"
    sudo systemctl enable libvirtd
}

virtualization_handler(){
    print_title "[!] INSTALLING VIRTUALIZATION"
    read_input_text "Want to install Virtualization Software?"
    if [[ $OPTION == y ]]; then
        PS3="$prompt1"
        virt_list=("VirtualBox" "QUEMU/KVM"  "NONE")
        echo -e "Select your Virtualization Software: \n"
        select VIRT in "${virt_list[@]}"; do
            if contains_element "$RICE" "${rice_list[@]}"; then
                if [ "VirtualBox" == "$VIRT" ]; then
                    install_virtualbox
                    break
                elif [ "QUEMU/KVM" == "$VIRT" ]; then
                    install_kvm
                    break
                elif [ "NONE" == "$RICE" ]; then
                    break
                fi
            else
                invalid_option
            fi
        done
    fi
}

i3_rice() {
    echo "todo"
}


# Compiling & installing waybar

compile_waybar() {
    print_title "[!] COMPILING WAYBAR"
    cd /tmp || exit
    git clone https://github.com/Alexays/Waybar
    cd Waybar || exit
    meson build
    ninja -C build
    sudo ninja -C build install
}

wayfire_rice() {
    echo "todo"
}

sway_rice() {
    print_title "[!] INSTALLING SWAY RICE SOFTWARE"
    sudo pacman -Sy --noconfirm xorg-server-xwayland sway wl-clipboard mako light mpc mpd mpv \
            ncmpcpp wofi swayidle grim slurp feh kitty qutebrowser ranger
    yay -Sy --answerclean A --answerdiff N swaylock-effects-git autotiling
}

common_rice() {
    print_title "[!] INSTALLING COMMON RICE"
    # Nano Colors
    curl https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh | sh
    # Colored Pacman
    sudo sed -i '33 s/#Color/Color/g' /etc/pacman.conf
    # Setting Theme and icon Theme
    gsettings set org.gnome.desktop.interface gtk-theme "$1"
    sudo pacman -Sy --noconfirm papirus-icon-theme
    gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'
    gpg --keyserver keyserver.ubuntu.com --recv-key 8FD3D9A8D3800305A9FFF259D1742AD60D811D58
    yay -Sy --answerclean A --answerdiff N papirus-folders cava vscodium-bin nerd-fonts-noto spotify \
              secure-delete tty-clock pipes.sh bettergram trash
    papirus-folders --theme Papirus-Dark -C violet
    # Ranger icons
    git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons
}

sway_dracula_rice() {
    common_rice "ant-dracula-gtk-theme"
    echo "test"
}

sway_violet_rice() {
    sudo pacman -Sy materia-gtk-theme
    compile_waybar
    common_rice "Materia-dark-compact"
    cd /tmp || exit
    git clone https://github.com/vol0s/sway-violet-rice
    cd sway-violet-rice || exit
    bash vsrd.sh &
}

ricing_handler() {
    print_title "[!] R U RICING OR NOT"
    read_input_text "Wanna rice?"
    if [[ $OPTION == y ]]; then
        rice_list=("Sway Dracula Rice" "Sway Violet Rice" "KDE (NO RICE)" "NONE")
        PS3="$prompt1"
        echo -e "Select your rice: \n"
        select RICE in "${rice_list[@]}"; do
            if contains_element "$RICE" "${rice_list[@]}"; then
                if [ "Sway Dracula Rice" == "$RICE" ]; then
                    echo "NOT FINISHED YET"
                    #sway_rice
                    #sway_dracula_rice
                    break
                elif [ "Sway Violet Rice" == "$RICE" ]; then
                    sway_rice
                    sway_violet_rice
                    break
                elif [ "KDE (NO RICE)" == "$RICE" ]; then
                    sudo pacman -Sy plasma konsole ksysguard
                    break
                elif [ "NONE" == "$RICE" ]; then
                    break
                fi
            else
                invalid_option
            fi
        done
    fi
}

check_archlinux
check_user
system_update
install_os_utils
install_yay
install_nfs
install_audio
install_bluetooth
install_colored
install_gpu
install_zsh_plugins
ricing_handler
configure_sddm
# virtualization_handler
install_secpack
sudo rm -rf /tmp/*
sudo reboot